-- Players table
create table if not exists players (
  id uuid default gen_random_uuid() primary key,
  name text unique not null
);

-- Decks table (dual-color Lorcana decks, slash-separated)
create table if not exists decks (
  id uuid default gen_random_uuid() primary key,
  name text unique not null
);

-- Submissions table
create table if not exists submissions (
  id uuid default gen_random_uuid() primary key,
  player_id uuid references players(id) on delete cascade,
  deck_id uuid references decks(id) on delete cascade,
  created_at timestamptz default now()
);

-- Seed players from players_unique.csv
insert into players (name) values
  ('Kalsbeek'),
  ('TeddyWestside'),
  ('Chops_thespian13'),
  ('Houla_CC_GG'),
  ('ThatGuyMajin'),
  ('Ahamby1212'),
  ('LinkGuy23'),
  ('BladerMagician'),
  ('Airdog2003'),
  ('I&LâŸ¡AMP3878'),
  ('iVSlime'),
  ('Aarzen'),
  ('Luchee Bandz'),
  ('GyngrBeard'),
  ('Desante'),
  ('Lorcana Twin 1'),
  ('awilp'),
  ('Wyant'),
  ('Adara'),
  ('Hexgirl'),
  ('disneywala'),
  ('Table'),
  ('Kind_Butterfly_0316'),
  ('Frosty21'),
  ('Abe'),
  ('LoL_AladdinsCastle'),
  ('TechieMan'),
  ('Mr_Moustache'),
  ('Doniele'),
  ('QuestingCat'),
  ('I&LâŸ¡Adam'),
  ('Adam H'),
  ('Adam_12thLore'),
  ('LoL Wandering Monster'),
  ('Nigelatoni'),
  ('SeriousGoose'),
  ('TootzMcBootz'),
  ('Yerxa'),
  ('LorcanaBoze'),
  ('ETB Adrian'),
  ('adriansado'),
  ('Cre8'),
  ('Bokbok20'),
  ('Aidan Muller'),
  ('MythicalMorph'),
  ('Aidyn - InkVaqueros'),
  ('AJ Ross'),
  ('IlluMNeers AJ'),
  ('Akira'),
  ('Alolan'),
  ('Iâ€™m Retiring'),
  ('InkingTink'),
  ('Fluffco - OhanaðŸŒº'),
  ('Caputdk'),
  ('MrSalas'),
  ('ENC_LoreGainz'),
  ('Beelzebuth'),
  ('Khaelstorm'),
  ('Aleks Hudson'),
  ('Waisted'),
  ('Prince'),
  ('WoahChuck01'),
  ('Barhobbit'),
  ('alex p'),
  ('Abachon'),
  ('AlexBlair'),
  ('TheCoffeyBean'),
  ('Dax ðŸ¦'),
  ('a4man'),
  ('Red Mamba0027'),
  ('TFM_KAHOTIC'),
  ('Alex'),
  ('Alex ðŸ‘¾'),
  ('JerryBones'),
  ('Illumineer_Of_Fortune'),
  ('Alex Mckelvey'),
  ('Alexis O'),
  ('LimitedPower'),
  ('Loadingâ€¦'),
  ('Reyes'),
  ('ptpoi'),
  ('AShin'),
  ('Atomic'),
  ('Anthrok'),
  ('*RocketWolf'),
  ('Alex Zammitt'),
  ('Alexa Play Lorcana'),
  ('AlexaMason'),
  ('TheMadSquirr3l'),
  ('TheSiegelBoy'),
  ('Xanderheeler'),
  ('alexandria p'),
  ('AlexandruTibirna'),
  ('DisneyDreamer'),
  ('Alexis Garzon'),
  ('AlexisRogganbuck'),
  ('Lecky'),
  ('Cycello'),
  ('AleB'),
  ('Ali'),
  ('Aliadin'),
  ('Ehnix'),
  ('nadaclu'),
  ('Reb_Church'),
  ('Decktales'),
  ('AlyssaNwonderland'),
  ('12Pint'),
  ('Amanda S'),
  ('Bain12'),
  ('MeatHammer'),
  ('AmiK'),
  ('AMIRACLE'),
  ('ishmo'),
  ('AmyOG'),
  ('Amy - Team Muses'),
  ('AmyPond17'),
  ('nogorou'),
  ('Narfdre'),
  ('AndiiM05'),
  ('AndreaB'),
  ('Andrea Kay'),
  ('sonique'),
  ('EGO Dre'),
  ('Andres'),
  ('AndyR29'),
  ('Ajz225'),
  ('Koreahn'),
  ('PrimeTime'),
  ('JustBuchmann'),
  ('Andrew C'),
  ('SaltyDuckAndy'),
  ('HL Chhunbucket'),
  ('ShintaKunX'),
  ('SQUID'),
  ('Potatotoro'),
  ('AlienAndy'),
  ('Andrew H'),
  ('Hoyt'),
  ('InkedShark'),
  ('Epicot'),
  ('DrewMx'),
  ('DrewMartin3z'),
  ('Photon'),
  ('Drewbound'),
  ('FPG_Casemind'),
  ('A.O.'),
  ('Lucky11'),
  ('ALLP1635'),
  ('Kensik'),
  ('Goku859'),
  ('Droopsy'),
  ('Hadron'),
  ('MrManofDoom'),
  ('Jukai'),
  ('RoV_Andy'),
  ('Tangst3r'),
  ('Andy the Grape'),
  ('AndyRoo66U'),
  ('Toxic degen'),
  ('TSS IamsoQT'),
  ('KOGAVGC'),
  ('ProfessLore'),
  ('Arr200'),
  ('Anna Mays'),
  ('AnnieW'),
  ('NVR_44lvarado'),
  ('Curious_Elephant_9357'),
  ('SheikTheGeek'),
  ('Anthony Chan'),
  ('OTC'),
  ('Switchz'),
  ('Eckroth'),
  ('KnotchYoTrees'),
  ('The Bard'),
  ('AntG1'),
  ('Hydraciti'),
  ('Grimmirvine'),
  ('AK'),
  ('Tokey'),
  ('Reb_gigantor'),
  ('Gremlins'),
  ('LoL_Kazii'),
  ('manthony'),
  ('[99] aioly'),
  ('DubberRucky'),
  ('Sassy Dragon'),
  ('Arielle'),
  ('3ink_MonkuChi'),
  ('Mondy018'),
  ('Snapcastermage'),
  ('Arnold N'),
  ('9Jaka'),
  ('Memej'),
  ('Artie'),
  ('JurrasicPaws'),
  ('nubbs20'),
  ('Waka57'),
  ('ABentley'),
  ('Mama Bear Ashley'),
  ('2oh4LoreFiestaGirl'),
  ('Colorislaw'),
  ('Ash ðŸŒº OhanaðŸŒŠ'),
  ('McQuacks - Legends of the Inkwell'),
  ('auburrito'),
  ('BreLenae'),
  ('Audrina'),
  ('HalfHealth'),
  ('RIP Hiram'),
  ('Shakiki'),
  ('Timesplitter56'),
  ('TTH AWPuppy'),
  ('AJarete'),
  ('Austin P'),
  ('Pletch'),
  ('Austin'),
  ('Tippy'),
  ('Aves822'),
  ('Avery'),
  ('TSS Gnosis'),
  ('IvyGoesRawr'),
  ('Kensaku'),
  ('RHS_Rozsi'),
  ('Baltazar G'),
  ('JudaiBalti'),
  ('TLD_NeverBored'),
  ('Barrett'),
  ('Basem'),
  ('Becky R'),
  ('EdHardyGirl'),
  ('boatsnack'),
  ('TFM Ben'),
  ('Ben - Inkspire'),
  ('Ulfenstein'),
  ('Syclic - Block Party'),
  ('Vamoscosmos719'),
  ('Uninkables'),
  ('Pockets'),
  ('Besteven'),
  ('FearFreak'),
  ('Benjamin Gibson'),
  ('Benjamin'),
  ('Ben @4thelore'),
  ('Benny13'),
  ('BillG'),
  ('MoLorcana'),
  ('BlakeyFresh'),
  ('Blake'),
  ('Cooldude'),
  ('LB_Lionthehawaiian'),
  ('Blake [Villain]'),
  ('SparkLight'),
  ('Eladebob'),
  ('DoubleBraker'),
  ('Bobby G'),
  ('Harwell Collectibles'),
  ('BobbyMcWho'),
  ('Bobby M'),
  ('KameelyanðŸ¦'),
  ('[ROV] The Mayor ðŸŽ©'),
  ('Braden'),
  ('Coldfire153'),
  ('MrUnlucky'),
  ('CS_bawantz'),
  ('Brady Heath'),
  ('brandon p'),
  ('Bubbarockies'),
  ('BSquared24'),
  ('Brute'),
  ('bdileanis'),
  ('Elk'),
  ('Felbz'),
  ('LK_Spinz'),
  ('Bhustle84'),
  ('TwigTwag'),
  ('Brandon Knop'),
  ('Blammy'),
  ('BMarkiewicz'),
  ('BrandonM1341'),
  ('Cloverkid- Brandon'),
  ('Retroverse'),
  ('ARMY'),
  ('Brandon Richards'),
  ('Bschara15'),
  ('Swolecana'),
  ('StampMan'),
  ('WINK'),
  ('LittenLover'),
  ('Brxtnwlf'),
  ('Brayan J'),
  ('Blenzer'),
  ('Deuce (Brayden)'),
  ('BreM8'),
  ('Nap Queen'),
  ('Teacher'),
  ('BrentB'),
  ('Tnerb'),
  ('Duler'),
  ('TheArchlord'),
  ('hadesnutz'),
  ('Brian Courtade'),
  ('scatteredfocus'),
  ('Klrgch'),
  ('[PL] BruhLife'),
  ('briancly'),
  ('Bhng'),
  ('[Noninkables] Briguy'),
  ('BSchat'),
  ('Brian Twigg'),
  ('LOL_Screwtherulez'),
  ('Wiebelitt'),
  ('BZ'),
  ('2oh4LoreBri'),
  ('Brighton'),
  ('BrinkRN85'),
  ('Flerkenz'),
  ('LadyBrit6'),
  ('Bubblebug_13'),
  ('PrincessK16'),
  ('OTP Peaked In Seattle'),
  ('Aomine'),
  ('BrunoMario'),
  ('GrandpaSmuff'),
  ('Floatybear'),
  ('Enchant3dHunter'),
  ('BetterBryan'),
  ('mnemonix'),
  ('LFG_Lobo'),
  ('Bryan LNF'),
  ('WYLD Zurita'),
  ('Skittles Cereal'),
  ('Bold_Dragon_1028'),
  ('Chris_Oyola'),
  ('BigOnFigs'),
  ('Fatninja479'),
  ('metavist'),
  ('DancingBarrow'),
  ('Paranoid Devil'),
  ('Alfio'),
  ('ScameronGG'),
  ('HUmarWhitill'),
  ('zerfman'),
  ('NotDavis'),
  ('CameronT4450'),
  ('Csungur'),
  ('cubsguy94'),
  ('Vynath'),
  ('TheHappyAccidentClub'),
  ('bambam11'),
  ('Dreamer'),
  ('Caroline'),
  ('Carolynsa3'),
  ('carrotkeki'),
  ('Carson Mann'),
  ('CarterWix'),
  ('CaseyBakerTattoos'),
  ('TFM_Orion'),
  ('Cassie'),
  ('spookycel'),
  ('Zetnus'),
  ('PandaMHB'),
  ('FearReizuTeamLegacyðŸ‰'),
  ('Cha'),
  ('Chad Clair'),
  ('OchoDirkso'),
  ('Chadlywick14'),
  ('Chad2019'),
  ('cDub80'),
  ('zombiecc'),
  ('Hobby Hero'),
  ('Kaiza'),
  ('Charlie Wendt'),
  ('Xfileguy'),
  ('Chasec'),
  ('Kirby'),
  ('Lounger Chase'),
  ('Phyrona'),
  ('DrNurseKnut_12thLore'),
  ('Rumble ðŸ¦'),
  ('Cheyenne'),
  ('ChipP'),
  ('Prince_of_Lamps'),
  ('Pandakrs'),
  ('cea60'),
  ('Chran'),
  ('Chris Bartlett'),
  ('ScottJurgenson'),
  ('CoveyMonster'),
  ('[99] Hunnymancer'),
  ('SHADOWFOX'),
  ('Jennings'),
  ('Chris Kreuter'),
  ('2oh4LoreKrupa'),
  ('Amity'),
  ('veryhungry'),
  ('Manfee'),
  ('Crobot'),
  ('LeoCristophe'),
  ('Tea-Time'),
  ('Chris ðŸŒ¸OhanaðŸŒ¸'),
  ('Viscount Nick'),
  ('I&LâŸ¡Chindestructible'),
  ('Lateforclass'),
  ('workshopluvr69'),
  ('Christian Y.'),
  ('Christina'),
  ('LoSo - TeamMomChristina'),
  ('C.Miles'),
  ('Big_Neck_ giraffe'),
  ('Zerocobalt'),
  ('Christopher B'),
  ('Valsindar'),
  ('VillainChrisG'),
  ('Kungpow'),
  ('Rellek'),
  ('Guu902'),
  ('CPie'),
  ('J-Learned'),
  ('Wonk Daddy'),
  ('CJ Penna'),
  ('Questingqueentcg'),
  ('Claude AubÃ©'),
  ('ClayByte'),
  ('TCG_Thesaurus'),
  ('LB_SuperDaddy'),
  ('Kwood007'),
  ('CoDJThatsMyDJ'),
  ('I&LâŸ¡codybraun1'),
  ('Wowzie'),
  ('Ccarlson'),
  ('Cody C'),
  ('Kaiju_Crab95'),
  ('Cody'),
  ('MooreLore'),
  ('Ccpace'),
  ('Riegel21'),
  ('Carbon'),
  ('Crankin691'),
  ('dab_of_ranch'),
  ('Old King Cole'),
  ('Coleen Scarrow'),
  ('ColinMF'),
  ('ENC_Eclipse'),
  ('ARaptor94'),
  ('TPM_Colin'),
  ('Shifted'),
  ('Collin K'),
  ('Colt'),
  ('Colt45'),
  ('Colton Rogers - Smash ðŸ‘Š'),
  ('ColtonS'),
  ('Steelsong Master'),
  ('Saucy'),
  ('cdally'),
  ('Valor'),
  ('DeathAndTaxes'),
  ('Hurleycz'),
  ('overpriced.kale'),
  ('Cordi_Turp'),
  ('Goop'),
  ('Pr0bl3mCh11d'),
  ('Humble'),
  ('Xtinct'),
  ('LB_SCAPESHIFT'),
  ('Cory Mathis'),
  ('3vo'),
  ('Courtney D'),
  ('Courtney - Enchanted Chatter'),
  ('THG_CoCo'),
  ('Kawatek'),
  ('Cris'),
  ('I&LâŸ¡Mycity23'),
  ('CBC'),
  ('Spencerina'),
  ('TSS HeyHiHelloItsCristin'),
  ('Queen B'),
  ('Crittle'),
  ('Dakota - Legends of the Inkwell'),
  ('Dakota S'),
  ('Dakotah Cotton'),
  ('MrsWylder'),
  ('Dale Bellido'),
  ('Dinglehopper'),
  ('LoL_RascalAddams'),
  ('CS_DaltonH'),
  ('xXBUBBLESXx'),
  ('thewhitewolf079'),
  ('Sirdiem'),
  ('Timetrav95'),
  ('Sharkboy'),
  ('Damyan B'),
  ('Dan Bigler'),
  ('RemyLeBeau'),
  ('Dan_Lankford'),
  ('Sailingfrog'),
  ('Rodemann'),
  ('PFC_Oracs'),
  ('DanaS'),
  ('DaniDock'),
  ('TFM_Dan'),
  ('Berghy'),
  ('Allvision'),
  ('Dan Fowl'),
  ('OnlyDans'),
  ('ACreativeGamer'),
  ('6SAMS'),
  ('Tiggers_DJK'),
  ('djkobold'),
  ('Notdan'),
  ('mHawker'),
  ('LB_deltamike26'),
  ('THG Crithalla'),
  ('dRiBz ðŸ¶'),
  ('DanielQ'),
  ('Spiritflame'),
  ('Baelfire94'),
  ('Daniel T'),
  ('Cerek'),
  ('WCC_DanieleMatrigale'),
  ('D. Lanham [Villain]'),
  ('DaniiXxNikkii'),
  ('d4nnym4n'),
  ('LFG_DannyPhoKing'),
  ('Le Guide'),
  ('Darian Saracevic'),
  ('Darin J'),
  ('Darryl D'),
  ('NoobStick'),
  ('Daryl436 - Team Muses'),
  ('daryn55mardis_12thLore'),
  ('Spinguini'),
  ('amigabledave'),
  ('DaveF'),
  ('Attackfortwo'),
  ('David Alvarado'),
  ('Wildcard58'),
  ('MST Negates'),
  ('Dave C'),
  ('dc'),
  ('Dabsence'),
  ('Batman_895'),
  ('Ink-Inc-Dave'),
  ('David H'),
  ('David Hernandez'),
  ('David J'),
  ('Angry Kirk'),
  ('Pocketdave25'),
  ('David Meyer'),
  ('unCAGEDgamez'),
  ('David Nunez'),
  ('DavidgPetryk'),
  ('iLLDKD'),
  ('TheDave'),
  ('David'),
  ('b0red_b0i'),
  ('DavidW'),
  ('Nebbie'),
  ('Watermelonmonster91'),
  ('Dsvette2290'),
  ('Fetty Guap'),
  ('Lady Esilyn'),
  ('Dennis Hillyer'),
  ('Denw3'),
  ('RisingVu'),
  ('Magic Q'),
  ('MooseMeeseMoosen'),
  ('MrEnchantedYT'),
  ('Ddekarske'),
  ('DerekF'),
  ('DIN0DEREK'),
  ('DerekT Bannibal'),
  ('Strafees'),
  ('Dwong'),
  ('Derk'),
  ('Deviox'),
  ('YoSoyDeven'),
  ('Deviknyte'),
  ('Devon Strohschein'),
  ('notdiane'),
  ('TFM_DBurns'),
  ('Level9001'),
  ('MoleStar'),
  ('DPU777'),
  ('DKP'),
  ('DJ The Zoologist - Ohana ðŸŒº'),
  ('CS_Minat0'),
  ('Booster Bijuu'),
  ('Domcana'),
  ('PapaLloyd'),
  ('donwell'),
  ('Woozles'),
  ('Anatidae_RSG'),
  ('Saberfink'),
  ('DK'),
  ('SilverAce'),
  ('DougP78'),
  ('Doug Rice'),
  ('drewjhowells'),
  ('TheKoboldLord'),
  ('DrewWithDreams'),
  ('DrewMcCoy'),
  ('DrewS'),
  ('Duane Malek'),
  ('Waffle'),
  ('Dhowell'),
  ('PFC_Dustymac'),
  ('Dustino659'),
  ('DKS91'),
  ('HL McScoops'),
  ('Pandarine21'),
  ('Dwray1'),
  ('Moxies'),
  ('Dylman'),
  ('Dylan Brown'),
  ('Buff'),
  ('Ink A Tink'),
  ('Dylan Crowley'),
  ('DylEdge'),
  ('BookofDylan'),
  ('Extoplazem'),
  ('Dylan Velez'),
  ('RHS_Dzenan'),
  ('RHS_Earlmeister'),
  ('Ed A'),
  ('SPJitter'),
  ('Edygordo23'),
  ('Eddie Pham'),
  ('Dingle'),
  ('Ed'),
  ('drpepperoni'),
  ('ILL_Ackerman'),
  ('HolyEdward'),
  ('Munsta'),
  ('Zoah'),
  ('Ewal'),
  ('TA_EnchantEd'),
  ('Zero'),
  ('Edwin Colleran'),
  ('Edwin'),
  ('TitoOfTomorrow'),
  ('elg'),
  ('ETB HABIBI'),
  ('OhanaStitch'),
  ('Dad Lore'),
  ('Em'),
  ('Emerson'),
  ('Missemily25'),
  ('Moonlight'),
  ('EmilyL'),
  ('elephant909_12thLore'),
  ('Emma'),
  ('Nugget'),
  ('ECC_Frdrake'),
  ('CMan'),
  ('Bonefolder'),
  ('Baoser'),
  ('Oceans Tempest'),
  ('peachmangopie'),
  ('Awesomenerddad'),
  ('E_Elvigan'),
  ('WhenWispsAttack'),
  ('YaMasLasagna'),
  ('Lucky_Panda_4935'),
  ('Eric Michielli'),
  ('Emull302'),
  ('E-Rod'),
  ('Jurassic'),
  ('CrAzYReD'),
  ('Eric Switzer'),
  ('REB Loremus'),
  ('Ironnuckle'),
  ('Erick Granola'),
  ('ErikP80'),
  ('EriD1'),
  ('Aerista'),
  ('Ep3'),
  ('Dr Nog'),
  ('BlazinAzn'),
  ('BonBon'),
  ('SeÃ±or Navidad'),
  ('Zona'),
  ('EthanLin'),
  ('ETHAN P'),
  ('An Evolved Chimp'),
  ('Sean choi'),
  ('[99] Shazzamy14'),
  ('Axom'),
  ('Thorsis'),
  ('Evan M'),
  ('Bluebeefman'),
  ('EJG_Evaristo'),
  ('NivesNerdCorner'),
  ('Eboi98'),
  ('INKCSTR_Ezekiel.M'),
  ('Ezekiel M'),
  ('IMO_Fabster'),
  ('F5'),
  ('VÃ¸id_VÃ¸id'),
  ('fedemeco'),
  ('VeNoM'),
  ('Bubbagumps'),
  ('FPG-Chilley'),
  ('GreenMan'),
  ('Francois de Bellefeuille'),
  ('FJBreakdown'),
  ('Frank Karsten'),
  ('Chickenbake'),
  ('Frank'),
  ('ILL_frivera215'),
  ('Skeptic Team Legacy ðŸ‰'),
  ('Frisco F'),
  ('G'),
  ('Gabriel'),
  ('Gabe'),
  ('GabeGolfer'),
  ('GFiki'),
  ('GabieK'),
  ('Xengal'),
  ('OhGeeWon'),
  ('Garrett Martin'),
  ('CC_Sir_Papi'),
  ('GaryStrudel'),
  ('Yipeee'),
  ('[NonInkables]Tinc'),
  ('GaryN'),
  ('LFG_Carsofel'),
  ('LegendGary'),
  ('GavinBraman_12thLore'),
  ('Gavin D'),
  ('KingGeoffrey'),
  ('GeoGilded'),
  ('Albinomango'),
  ('George'),
  ('G-ROD'),
  ('GWSmoove'),
  ('Gjbourg6'),
  ('kiat'),
  ('Giancarlo Fraticelli'),
  ('badandbougp'),
  ('geeb'),
  ('DarknessQt'),
  ('Gilbert Ninh'),
  ('Zenaby'),
  ('Glenson'),
  ('Gourd On Cane'),
  ('Gordon'),
  ('Grant'),
  ('Grant R'),
  ('GraR5'),
  ('Greg A'),
  ('RagingOldMan'),
  ('SaltyDuckRenovatiolife'),
  ('Greg simon'),
  ('Gregory R'),
  ('greyson L'),
  ('Memaker'),
  ('GGLORCANA'),
  ('Gusw7w'),
  ('Marshall'),
  ('H_Krantz'),
  ('610'),
  ('HalieStroud24'),
  ('PunkPikachu'),
  ('Hannah Hurley'),
  ('Hannah Y.'),
  ('KetchupMustardKing'),
  ('RHS_Harald'),
  ('Hargi'),
  ('YaBoyJH'),
  ('Alphos'),
  ('HeiHay'),
  ('LoSo - PacPops'),
  ('Patriofelis'),
  ('hcovey'),
  ('Heather C'),
  ('HeatherR'),
  ('SunflowerQueen79'),
  ('24kHector'),
  ('Hector Heras'),
  ('Scraggy'),
  ('FearFreakJr'),
  ('Listengoodt'),
  ('Herk'),
  ('HillaryC~TeamðŸ‘ŠðŸ¼'),
  ('El Vagabundo'),
  ('LorcanaMan'),
  ('Oberon125'),
  ('Bluederpyturtle'),
  ('UtopIan Board Games'),
  ('IanE46'),
  ('EN'),
  ('Honest Abe'),
  ('Ikaika'),
  ('ITHersey'),
  ('Irenicle'),
  ('Chewdizzle12'),
  ('TwoFistedMonkeyStyle'),
  ('izzyyyb'),
  ('Legendaryfocus'),
  ('LoL_METALLICFLARE'),
  ('PookieBaller'),
  ('Level99Magikarp'),
  ('Yappy_Hamster_0528'),
  ('LadyKing24'),
  ('Captain Milkshake'),
  ('TimeLord- HHM ðŸ“'),
  ('Ghosty'),
  ('Jackmtr'),
  ('JackIn_DaBox'),
  ('JacksonGrassli'),
  ('JackBulman'),
  ('madjack272'),
  ('LegitimateBusinessPerson'),
  ('I&LâŸ¡jacobayy'),
  ('Steakanator'),
  ('jakets89'),
  ('Jakeup'),
  ('TwistedLore'),
  ('Jake H'),
  ('HAMPAGE'),
  ('Jhelman22- HHM ðŸ“'),
  ('Jmadecky'),
  ('[ANG]SoShinyTCG'),
  ('FPG_TheSkipper'),
  ('Jacoby04'),
  ('JakeP'),
  ('ItsNotSlowPlay'),
  ('Lil.boy.jay'),
  ('SaltyDuckJacob'),
  ('JakeTSD'),
  ('Hellboy'),
  ('HoosierHoney'),
  ('TheSiggo'),
  ('Taylor Swift'),
  ('icky'),
  ('REB Dreamz'),
  ('Quinsee'),
  ('JLoke'),
  ('Jalyn'),
  ('TPM_james'),
  ('Cease'),
  ('Fungus'),
  ('James Gray II'),
  ('SageMode'),
  ('jsoong'),
  ('Spaceman Spiff'),
  ('CardinalYOLO'),
  ('Philosophercatnc'),
  ('Worthless'),
  ('jimbojones133'),
  ('BigWoot'),
  ('JamieH'),
  ('Femennenly'),
  ('Astrogeek'),
  ('CaesarSTL'),
  ('Redeemer'),
  ('Jared_McLain'),
  ('Jred013'),
  ('Jsho'),
  ('Jared'),
  ('Jarod P'),
  ('1upization'),
  ('Quicksphynx'),
  ('Flownomenal_One'),
  ('Jason323232'),
  ('Bighero626'),
  ('JasonF'),
  ('Stingwing40K'),
  ('jlthoughtcast'),
  ('izik'),
  ('JScare'),
  ('Schwanns'),
  ('J. Shannon'),
  ('Jenoxis'),
  ('Jason'),
  ('Repsaj'),
  ('Wizard'),
  ('Jay Headley'),
  ('JaylenV'),
  ('JayBunga'),
  ('JazS'),
  ('JDZ Quest'),
  ('Jcruz'),
  ('Jeannie'),
  ('J-S'),
  ('Jebas'),
  ('JeddWith2Ds'),
  ('JBaum'),
  ('REB_Kahn'),
  ('Lostie002'),
  ('kingFritto'),
  ('Jeffrey Hudon'),
  ('Jeff K'),
  ('SuperSpaceGoop'),
  ('Veritas'),
  ('Chronobog'),
  ('thej_long'),
  ('Jeff - Additional Ink'),
  ('Jscott'),
  ('JBiggs'),
  ('FPG_Just Jennifer'),
  ('DesertPeach37'),
  ('Questlore_Jen'),
  ('JRJones92'),
  ('Jen T'),
  ('8675309'),
  ('Jenny'),
  ('The_Only_Smillie'),
  ('Jeovani A'),
  ('jeremiahbarradas'),
  ('Miah981'),
  ('PFC_Jeremy_A'),
  ('LB_Holyghost'),
  ('Moxjeremy'),
  ('CaptainHook'),
  ('Jeremy L'),
  ('JERMAX'),
  ('Jeremy Rowe'),
  ('LoSo - Joda'),
  ('Bold_Sloth_5269'),
  ('JerFTW'),
  ('ItsAHassell'),
  ('YEET-Woman'),
  ('JFrailey'),
  ('Heist'),
  ('Goose'),
  ('JesseTCG'),
  ('BigJessiD00'),
  ('JessT14 ðŸ’–âœ¨'),
  ('Gingeraffe - Legends of the Inkwell'),
  ('2Bad_knees'),
  ('JessShadow'),
  ('Sincerelyjessxo'),
  ('Pascal626ðŸ¦Ž'),
  ('NVR_Bechi'),
  ('Chewy'),
  ('Heyzeus'),
  ('jmutter'),
  ('Jevon'),
  ('Jill&Juice'),
  ('FreddieHubbard'),
  ('JimThePMM'),
  ('RoV_clesiemo3'),
  ('Wakinglife_TSD'),
  ('PrettyBoyPro'),
  ('joaquin'),
  ('TFM_PlzNoticeMe'),
  ('Strong Guy'),
  ('Clevelando'),
  ('Thrillhouse'),
  ('Joe'),
  ('Joe Tanquary - HHM ðŸ“'),
  ('CC_Littlejoe'),
  ('Joe W'),
  ('HighRoll Joel ðŸŽ²'),
  ('Krows Sin'),
  ('SofaKingGood'),
  ('Joelk'),
  ('Jinxshame'),
  ('ROYAL-Ghost'),
  ('FG_Ottomatic'),
  ('JGSali'),
  ('Sleeping'),
  ('ðŸ¤™SuperfliguyðŸ¤™'),
  ('John'),
  ('Valan'),
  ('Cassj'),
  ('VincentRtA'),
  ('joker5893'),
  ('WildBanshee'),
  ('Austin Kuchinski'),
  ('Yan'),
  ('Johnny'),
  ('FPG_Broken'),
  ('Alabama Hamma ATLUS'),
  ('John S'),
  ('Johnnie'),
  ('JohnD6'),
  ('FitMagician'),
  ('Johnnymontster'),
  ('Disarray'),
  ('BlastoiseKid'),
  ('Jon K'),
  ('Jon L'),
  ('OPness'),
  ('FG Sisu'),
  ('Unobot'),
  ('Agomaaaaaa'),
  ('Warp3000'),
  ('Kite (Jon)'),
  ('GoofyBoy'),
  ('jonathanscrow'),
  ('Jcurlin'),
  ('LorcanaJon'),
  ('Inkwell Gaming'),
  ('illusðŸŽ¢onz'),
  ('LFG_TheShadowSlash'),
  ('Jhasebe'),
  ('TFM_JHE'),
  ('GingerLorcana'),
  ('LamChopss'),
  ('JonVonSchweetz'),
  ('mrbluejamðŸ¶'),
  ('LFG_J-Mills'),
  ('BlueYoureMyBoy'),
  ('Jonix'),
  ('ExtraCreamyGooeyGoo'),
  ('JonTheRanger'),
  ('JonnyBoy'),
  ('Fuzzy_Koala_7391'),
  ('Sweet'),
  ('I3aymax'),
  ('Jonathan Varelakis'),
  ('Dunkz_GTðŸ¤ª'),
  ('Yanick'),
  ('Dragonjonz'),
  ('TheGrind2014'),
  ('Sum1No1CanBeat'),
  ('FlockintheCove'),
  ('Hunkules'),
  ('Lionhead87'),
  ('Jordan'),
  ('TJLA'),
  ('MWF616'),
  ('2oh4LoreLarry'),
  ('Darnfreshman'),
  ('Jordcana'),
  ('[99] Jsquared3'),
  ('JordanK53'),
  ('JMayne'),
  ('JSAMiAM'),
  ('Jorwest86'),
  ('JayNicky'),
  ('HeavyJ'),
  ('Jorge'),
  ('joseker'),
  ('Screamy'),
  ('[PL]Yoshipked'),
  ('Feli'),
  ('OBSJayFlo'),
  ('Howthisdictates TeamLegacy ðŸ‰'),
  ('JeromeTPO'),
  ('Baboonbott'),
  ('Mojica'),
  ('Disney Nerd Jay'),
  ('ACOR77'),
  ('Scoops'),
  ('Joebellenie'),
  ('TSDMooMan ðŸ„'),
  ('Speci'),
  ('Pinkytoe'),
  ('JoDock'),
  ('ShadowTheFox'),
  ('Joe_12thLore'),
  ('ETB PandemoniumHeart'),
  ('Diabloshift'),
  ('SnackAttack'),
  ('Layzall'),
  ('Shadypeach'),
  ('JoeDub'),
  ('jjr78'),
  ('Crescent'),
  ('Monkersville'),
  ('CerberusDenJosh'),
  ('JTCrit'),
  ('ChienPwnd47'),
  ('Injul'),
  ('JP'),
  ('Hangist'),
  ('JoshShadow'),
  ('Jibberystyleoinkerys'),
  ('Jander717'),
  ('Mrpoppinz'),
  ('WAMP72'),
  ('Chubby'),
  ('ImpactHs'),
  ('Josh J'),
  ('Karnage'),
  ('Shadawx'),
  ('Barber'),
  ('ZombieHoarder'),
  ('Joshua Malek'),
  ('CustomRumble403'),
  ('A Lorcana Player'),
  ('Sorcerer''s Hat YT'),
  ('Getyourgameon!'),
  ('Joshie513'),
  ('Cerealmonster'),
  ('Joshua Satterfield'),
  ('CaptainFershizz'),
  ('HunnyWizard'),
  ('Josh_FWS'),
  ('Junior Varsity'),
  ('JMoney23'),
  ('Squeekysheep'),
  ('Nashcana_Lounger'),
  ('Siah'),
  ('AggroCindy'),
  ('The Terror That Flaps In The Night'),
  ('Jotham'),
  ('Jourdon S'),
  ('Lemonade'),
  ('SpaceCat'),
  ('Dmoc86'),
  ('Juan Solo'),
  ('swaggr'),
  ('Juanavitas'),
  ('Jude'),
  ('juliasanderson'),
  ('Aurien'),
  ('LoL Julien'),
  ('JuJu'),
  ('Juuuuuun2k'),
  ('CarlGoBoom'),
  ('Justen'),
  ('Justice'),
  ('CASJ'),
  ('JCho'),
  ('MrKrabbs'),
  ('LabTwister'),
  ('[99] StrykerJ'),
  ('BigThunderâš¡ï¸'),
  ('Justin G'),
  ('Bruno'),
  ('JustinHChrist'),
  ('Illumineer_Justin'),
  ('Justin Nguyen'),
  ('TheDisDude'),
  ('Pokemon661'),
  ('Justin R'),
  ('Justin Schibanoff'),
  ('WCC_Jshaft'),
  ('SwolyswoND'),
  ('SirLore'),
  ('RazgrizBlitz7'),
  ('Trippe'),
  ('Jnwaller'),
  ('Justin Ward'),
  ('Sly'),
  ('BSG.justine'),
  ('JZ33'),
  ('KB2187'),
  ('KTurn413'),
  ('Whysper'),
  ('DemonicButterfly'),
  ('Karan G'),
  ('Karim soliman'),
  ('Katrunner'),
  ('Katshadowe'),
  ('Katie'),
  ('Kitkat81908'),
  ('KitKat'),
  ('Katie N'),
  ('LadyLore'),
  ('LoL_KatCrits'),
  ('Jkayyyla'),
  ('KaylaRay385'),
  ('Kayla S'),
  ('alyakkayla'),
  ('Yappy_Panda_9966'),
  ('BADMOUSE'),
  ('Stretch'),
  ('Bka9899'),
  ('xGhostGamesTTV'),
  ('Keith The Square'),
  ('TPM_KELEIGH'),
  ('Kelly'),
  ('Kelly A'),
  ('Kelsey âœ¨'),
  ('Ken S'),
  ('WCC_Kendall'),
  ('TEI_Kendyc223'),
  ('Brohammington'),
  ('KenL3'),
  ('Glitched-Obsolete'),
  ('MicKENNY Mouse'),
  ('The Peopleâ€™s Chump'),
  ('AwfulSlothagus'),
  ('GREATking54'),
  ('Aggroskill'),
  ('Atticus1313'),
  ('kbear23'),
  ('Kerry D'),
  ('Lux_Danxor'),
  ('I&LâŸ¡Dr. Kebbin'),
  ('KFaCor'),
  ('SpaceRanger'),
  ('KevinTheWinion'),
  ('Studded'),
  ('ColdRiv3r'),
  ('Uso1824'),
  ('Ksmart'),
  ('Tiggers_TortoPounder'),
  ('KDog'),
  ('LorcanaKev'),
  ('LB_Spectre'),
  ('Kian'),
  ('Killowatt'),
  ('Enchanted Kim'),
  ('Kimberlyanne'),
  ('Kiminy cricket'),
  ('Kimiko_GTðŸ¤ª'),
  ('LoSo - Kimstigator'),
  ('King W'),
  ('Kirby C'),
  ('RoV_Kirsten'),
  ('Pinkmagicc'),
  ('Krezkrieg'),
  ('Kloud'),
  ('KoreySmash - ðŸŒº Ohana'),
  ('kvaessen09'),
  ('CS_KLBair'),
  ('ETB Kris'),
  ('KapNKris'),
  ('Aeron Ignacio'),
  ('KristentheGrape'),
  ('Kristen Rose'),
  ('KPandCha'),
  ('Kristina'),
  ('Tspoon'),
  ('Lorcanamum'),
  ('Krib12'),
  ('Gooons'),
  ('KriK7'),
  ('Kristy'),
  ('Kryptonic Yeti'),
  ('KurtSpice'),
  ('Gentle_Panda_7525'),
  ('ProtectTransKids_KyleB'),
  ('GollyGreenGiant'),
  ('Parzival'),
  ('Kyle'),
  ('Harshy'),
  ('TheLuckyLoafer'),
  ('KaiFLY'),
  ('Kyle S'),
  ('I&LâŸ¡Rabbid.'),
  ('Eonstar'),
  ('Ricky Business'),
  ('KowboyKyle216'),
  ('Kyler'),
  ('Naya_Kai'),
  ('Petersbergh'),
  ('Luca Serano ðŸ¤«ðŸ§'),
  ('Lady_Adorabelle'),
  ('LadyBrittany'),
  ('Lantzalot'),
  ('Letâ€™s Get Dangerous'),
  ('Lance'),
  ('Amad3us'),
  ('Lanecana'),
  ('DetectiveSparky'),
  ('Larry MaCH00ga'),
  ('UNINKABLESðŸ”¸iceman'),
  ('Larry'),
  ('LauraJY5'),
  ('Lauren'),
  ('Leah Craig'),
  ('Princess Fiona'),
  ('Leophives'),
  ('Nugget815'),
  ('altris'),
  ('Iconic_WhiteChocoBear'),
  ('lwrcaselexi'),
  ('Liddy W'),
  ('Liem'),
  ('TeslaCat'),
  ('Puddin'),
  ('Saytayday'),
  ('bbbbbasic'),
  ('EnchantedToMeetYou'),
  ('Liz'),
  ('elskokan'),
  ('Logibear'),
  ('Espresso'),
  ('Logitimate'),
  ('Logan P'),
  ('Xenulous'),
  ('just_op'),
  ('imjustrynagetLoST'),
  ('LorcanaLoaf'),
  ('BB_Lollocast'),
  ('LorinB'),
  ('Louie'),
  ('Ohana Lorcana'),
  ('Luca R'),
  ('alaskan bull worm'),
  ('Lucas M'),
  ('Gorkain'),
  ('Lunerath'),
  ('Lucas'),
  ('Luis Cardenas'),
  ('No.One_Shuffl'),
  ('Boo_Urns'),
  ('RFT_Huayra'),
  ('RHS Lukas Kaupa'),
  ('ThePurplePrince'),
  ('Luker9000'),
  ('AuraOfLucario'),
  ('Luke Mays'),
  ('vVonderland'),
  ('Lykoss14'),
  ('Macie'),
  ('Burner09'),
  ('mackgali'),
  ('Inkredibles_Ceci'),
  ('Madison'),
  ('Mago'),
  ('INKCSTR_maipotatopengu'),
  ('Cruel'),
  ('MagicalMandy'),
  ('Cindere11a'),
  ('Beastmode'),
  ('ENC_Mixup'),
  ('MarcLevy'),
  ('ENC_Marc'),
  ('Marc T'),
  ('Marco Corral - InkVaqueros'),
  ('NoWackThrowbacks'),
  ('Juice'),
  ('ohmaria789_12thLore'),
  ('[99PL] Inkchantress'),
  ('mariasmagicverse'),
  ('NamineMegane'),
  ('Its_Me_Mario'),
  ('BattlePhase'),
  ('IndianaBones'),
  ('Braunimus'),
  ('ECC-Mark'),
  ('Mark E'),
  ('Mookster'),
  ('Nvr | NvrGunnaStop(Mark)'),
  ('Sokrazyazn42'),
  ('Danger'),
  ('TTH PartyMarty'),
  ('Rabiddog20xx'),
  ('Vulc'),
  ('Marty'),
  ('MURR-E'),
  ('Lightly'),
  ('MattyP'),
  ('Mr_Once'),
  ('majobasil'),
  ('inillob55'),
  ('Dyxonian_INKINC'),
  ('Mezuroe'),
  ('Loonie'),
  ('Matt H'),
  ('Matt Karczewski'),
  ('LFG_4GOTT3N1'),
  ('drumstix026'),
  ('xXMattyFreshXx'),
  ('Matt P'),
  ('Matt Robbins'),
  ('BodyMatt'),
  ('matts92'),
  ('Matt Sonnhalter'),
  ('Snapquester Mage'),
  ('Free win'),
  ('CKRanger'),
  ('TheEgohaslanded'),
  ('Director_Lebish'),
  ('Mattachew'),
  ('Dwarfnic'),
  ('Matty'),
  ('Duggan'),
  ('QualityMemes'),
  ('GBG_MaFuggin'),
  ('Troopy'),
  ('QuestLore - Matt'),
  ('Matthew_Inkinc'),
  ('ReadySetDraw'),
  ('DisKnee'),
  ('DivineWindex'),
  ('MOrrBridges'),
  ('Bendytendy'),
  ('Matt'),
  ('Haymak3r'),
  ('chewstery'),
  ('mattryan1508'),
  ('Dashiz'),
  ('INKCSTR_RedShorts'),
  ('strilpatch'),
  ('Mav Dog'),
  ('Snake_Nitro'),
  ('LoreCora'),
  ('Rafreaky'),
  ('IceSolostice'),
  ('Kyubey57'),
  ('SmileyFace'),
  ('EnviroMax'),
  ('Larkynix'),
  ('Max â€œlittlei999â€ Wendt'),
  ('El Machops'),
  ('mckenzie'),
  ('Drmalcolm'),
  ('Friends Call Me Meg'),
  ('megk4'),
  ('mKoester'),
  ('Tiny Magic'),
  ('TheMagicMegan'),
  ('Megan'),
  ('Disney Dazed'),
  ('Megan Taves'),
  ('Melmen'),
  ('SiriusAboutLaw'),
  ('Meelee.giant.fairy'),
  ('Rainspider204'),
  ('michael p'),
  ('Zubrin'),
  ('myko53'),
  ('ShadowNinja'),
  ('Arroyo1325'),
  ('BigMike'),
  ('Michael Bolduc (Raskelot)'),
  ('Brucana'),
  ('Mikey B. - Team Muses'),
  ('TEI_FrozenFrac'),
  ('Michael Cawit'),
  ('Claden'),
  ('MikeC12'),
  ('JediWindTrick'),
  ('Stick'),
  ('BigNastee'),
  ('Bgmike87'),
  ('LuxFerrante'),
  ('Viktorious'),
  ('Fio'),
  ('MFuss2120'),
  ('Michael Hawkinson'),
  ('Yashku'),
  ('Kkg'),
  ('FG_MomentuM'),
  ('Nossim'),
  ('Michael M'),
  ('Ng0WaYYY'),
  ('SorÄ‡erer_Mickey'),
  ('MOBlock'),
  ('Shadryth'),
  ('Mike_Qc'),
  ('Mikeream'),
  ('MikeSync'),
  ('Ecko Legend'),
  ('PlaysWithSquirrels'),
  ('Azuken'),
  ('ramablahblah'),
  ('Sheebs'),
  ('mrtarczynski'),
  ('Deathlokk'),
  ('Michael Wayne'),
  ('THG_Micha'),
  ('MaraudingMap ðŸ¦'),
  ('Mikayla Bair'),
  ('Ink _inc Mike'),
  ('00sVoice - Legends of the Inkwell'),
  ('Thedarksyde'),
  ('DJMugget'),
  ('Rojo'),
  ('THG_Blinx'),
  ('MikeComicMan'),
  ('gHanDi'),
  ('DayOneIsh'),
  ('Leonard'),
  ('2oh4LoreMike'),
  ('SalamanderBeats'),
  ('bigmikew'),
  ('Lucky_Owl_5236'),
  ('HaZed'),
  ('Milton'),
  ('IntotheInkwell Milvs'),
  ('Mindy_Mouse'),
  ('kmnop'),
  ('Randalynn'),
  ('Minaval'),
  ('Skulking Yegg'),
  ('CURSED- DEFMONKEY'),
  ('Mitch'),
  ('Mitch Moore'),
  ('MFork'),
  ('Not the other Mitch'),
  ('Mitchell Martin'),
  ('lL3TCHUM'),
  ('SuperMovA'),
  ('Moises C'),
  ('I&LâŸ¡ifoundmollie'),
  ('Bold_Flamingo_6370'),
  ('ENC.DuoMonica'),
  ('Morgan'),
  ('Jonathan Blumer'),
  ('Treky'),
  ('LoL Fulldeck 52'),
  ('NOA'),
  ('Inkognito_najie'),
  ('Narisa'),
  ('khaotiqbeats'),
  ('Ramboscoob'),
  ('Willobeez'),
  ('Daddies4Baddies'),
  ('Ferkalicious'),
  ('Nate Jacobs'),
  ('TFM_Nate'),
  ('Gambit'),
  ('Karp'),
  ('ThePurplePanzy'),
  ('LivingLorcana'),
  ('ChickenDinner'),
  ('Nathan R'),
  ('SkibidiRizz'),
  ('UNINKABLESðŸ”¸Nathan'),
  ('Pepto'),
  ('NVIII'),
  ('Tron1686'),
  ('nate3289'),
  ('Nathaniel K'),
  ('Nathaniel Rosado'),
  ('Dalegor'),
  ('NeilM'),
  ('Neill'),
  ('å‡¤å‡° Prodigy ðŸ¦â€ ðŸ”¥'),
  ('AndyNguyen97'),
  ('NES'),
  ('Nachelly44'),
  ('Beefcake'),
  ('LoL Xelephanor'),
  ('Nicholasjdata'),
  ('Nick_D'),
  ('Fortunon'),
  ('Chef_Nick'),
  ('Nickkalas34'),
  ('Mr.Cheese'),
  ('Nicholas'),
  ('nplayforth'),
  ('Nicholas Sanchez'),
  ('Nicholas Wyllie - Legends of the Inkwell'),
  ('BSG ChiTownAvenger'),
  ('NickD'),
  ('NickB_63'),
  ('KingOfGames'),
  ('Traetus'),
  ('Handlin'),
  ('Adaon42'),
  ('Blu hawaiian'),
  ('Lorcananick'),
  ('Noiyze'),
  ('NickMor'),
  ('2oh4LoreKingKaos'),
  ('LorcanaLoreKing'),
  ('Turp'),
  ('JackalopeSpam'),
  ('Vaderllama'),
  ('NicChamp'),
  ('Nicolas Beland'),
  ('Nicolas Boivin'),
  ('NiceRoy'),
  ('Ogryzzlybear'),
  ('Seraephina'),
  ('dlwlrma'),
  ('LadyInkwell'),
  ('NoFace'),
  ('Nile'),
  ('Kneelays'),
  ('INKCSTR_NixonC'),
  ('Nicholas Pittarelli'),
  ('noah'),
  ('Duckie'),
  ('This isn''t Riftbound ðŸ¦'),
  ('Noah_Terry'),
  ('SoneRandomUser'),
  ('NorahW'),
  ('Nyx'),
  ('Olivier D'),
  ('SaltyDuckRaccoomar'),
  ('Tiggers_Goliath'),
  ('OmiK'),
  ('Valiant_Dragon_8697'),
  ('Yappy_Butterfly_3145'),
  ('Peanutbutter'),
  ('minkbat'),
  ('Panda'),
  ('Panteli'),
  ('PK_12thLore'),
  ('RollingCode'),
  ('LorcanaBCB'),
  ('Patrick CÃ´tÃ©'),
  ('The1who1'),
  ('ENC_duoPatrick'),
  ('DispatchPatch'),
  ('Bird Pat'),
  ('CS_Poncho'),
  ('Citizen Snips'),
  ('GhostStory'),
  ('krabbyomondays'),
  ('I&LâŸ¡AxelPlays'),
  ('pp3'),
  ('pp4'),
  ('PDubNC2STL (Paul)'),
  ('Pwongage'),
  ('PikaTon'),
  ('Pclemente93'),
  ('LavaDodger'),
  ('PerryStewart'),
  ('Aretoo'),
  ('LB_Lythral'),
  ('Pete'),
  ('Rentisdue'),
  ('Bunneh'),
  ('Unknownforce'),
  ('TwistedVizier'),
  ('Ewok Pok'),
  ('McPhilly'),
  ('Pipinator'),
  ('PhilAss'),
  ('Philippe BrulÃ©'),
  ('Hobogoatman'),
  ('Yourguyphil'),
  ('s4iler'),
  ('PrincessPiper'),
  ('ponzie'),
  ('Sabine'),
  ('PrestonMcNair'),
  ('Silly_Llama_0029'),
  ('[Noninkables] Q'),
  ('Mutsumi'),
  ('Sightblinder - HHM ðŸ“'),
  ('Quiokix'),
  ('Fionraella ðŸ¢'),
  ('Uninkable'),
  ('Rachel Zammitt'),
  ('Rae'),
  ('Trailblazer'),
  ('RalphyAM'),
  ('Ricemaster'),
  ('King Ram'),
  ('KidKaor'),
  ('R-Dog'),
  ('DWRAY2'),
  ('Ray956'),
  ('HL_eRaycer'),
  ('RamenShop'),
  ('Rc Cola'),
  ('SilverGirlSweets'),
  ('_becca_'),
  ('IMP_Kyoshi'),
  ('Regis B'),
  ('Regis Blahut - Ink Inc.'),
  ('Dalada'),
  ('Heffalump'),
  ('âœ¨FairyCardMotherâœ¨'),
  ('SurpriseMe'),
  ('LoL Rey Rey'),
  ('Glitched_Tron'),
  ('Richard Charron'),
  ('Fumbles'),
  ('Richard H'),
  ('Reel Talk'),
  ('Chard ROM'),
  ('Richard Richey'),
  ('Richard Kenobi'),
  ('Rich2202'),
  ('Treadeasy'),
  ('Richard Zhou'),
  ('noserain'),
  ('Richie Thompson'),
  ('itsrichie'),
  ('Rmartinez032'),
  ('BeyondSoldier'),
  ('Ricky Life'),
  ('Coocoo'),
  ('Riri_1314'),
  ('Starcaster'),
  ('Not_TFM_Riley'),
  ('ETB Riley'),
  ('Lazaro'),
  ('RJC3'),
  ('RobdeHaan1987 ðŸ“'),
  ('Sawyerspop'),
  ('BPrep'),
  ('Robert B'),
  ('Slurple'),
  ('StunningRob'),
  ('Bgress529'),
  ('roxasmanalo'),
  ('THG MidGe'),
  ('Markoth [ATLUS]'),
  ('VulcanRaven'),
  ('Porterfield'),
  ('The Chuckling Atom'),
  ('Ditto_RobRob'),
  ('Ghadren'),
  ('RobS18'),
  ('SpartanSickles'),
  ('5T0W3R5'),
  ('Toupaloop'),
  ('Illiterate'),
  ('RobPunzel510'),
  ('Itz_Rj'),
  ('SteerOn'),
  ('Rekkless'),
  ('DarkwingLuck'),
  ('Rbiggs'),
  ('Plowking247'),
  ('Scientist'),
  ('Rowan Stavenow'),
  ('âœ¨ï¸RoxxiStarâœ¨ï¸'),
  ('Santana'),
  ('Freshair6'),
  ('Rufus'),
  ('Ryan D'),
  ('R_M_B'),
  ('Ryan Blaha'),
  ('Ryanticz'),
  ('LorcanaGinger'),
  ('ryanfan'),
  ('ryandg'),
  ('Ryanheinz'),
  ('FullyDerped'),
  ('Ryno22'),
  ('Posadas'),
  ('Ryan jorg'),
  ('2oh4ShebazJenkins'),
  ('Cabbage Corp'),
  ('PFC_Doug'),
  ('Ragnar0k_s'),
  ('RyanEffinMiles'),
  ('Stent'),
  ('Rhyngoh - InkVaqueros'),
  ('Ruunan'),
  ('Rynotheshort'),
  ('HoodedBiscuit'),
  ('Ragman13'),
  ('ArRoW'),
  ('ArcLighter'),
  ('GrailHunter'),
  ('Ryan Simpson'),
  ('RyWalker'),
  ('rc'),
  ('Sabastian'),
  ('Penguin Queen'),
  ('M4thm4n'),
  ('Jolly_Llama426'),
  ('MASTERSAL08'),
  ('Mando88'),
  ('LorePuppy'),
  ('Mopedman'),
  ('Tapped Ink Genius'),
  ('hgpot'),
  ('Sam Martinez'),
  ('Cheeto'),
  ('TSS foxindocs'),
  ('Sam Weiman'),
  ('NintendoFanGirl'),
  ('Rhythm'),
  ('Chorgi'),
  ('ampamp'),
  ('THG_Dwiz19'),
  ('Sgibson'),
  ('Smalls13'),
  ('PuKahlu'),
  ('Ladyreadsalot (Sarah)'),
  ('LB_Yensid07'),
  ('Nashcana_Sarah'),
  ('Sasha'),
  ('Sawyer Breslow'),
  ('SKY'),
  ('bumi_jr'),
  ('Biff'),
  ('Scooter'),
  ('SuperLazy'),
  ('ExScottic'),
  ('Scott L'),
  ('TFM_Scott'),
  ('Scott Markeson'),
  ('funnyjk'),
  ('Scott Free'),
  ('Savvy Sailor'),
  ('Hatters Gonna Hat'),
  ('Matrixsean'),
  ('SeanBrandt'),
  ('LoSo - Strenuous'),
  ('Keetonpotatoes'),
  ('Sean'),
  ('LoL Sean (L.A.B)'),
  ('Seb'),
  ('Sebastian K'),
  ('SbV'),
  ('Sergioagt123'),
  ('Shark'),
  ('Shane'),
  ('ShanersEdict'),
  ('Fitzpasd'),
  ('grokdisco'),
  ('Shannon C'),
  ('ShaD3'),
  ('IMaBURRITOohYeah'),
  ('MoeMouse'),
  ('ENC_Triton'),
  ('Thor'),
  ('Bawnty'),
  ('Windu'),
  ('LilBrandt22'),
  ('svilla0422'),
  ('Papa Shi'),
  ('JayR'),
  ('HeiGirlHei'),
  ('2oh4Lore Rilnak'),
  ('Skrantzy'),
  ('Turtle'),
  ('SorenSlays'),
  ('MiniMC'),
  ('Heartthrob'),
  ('Spencer S'),
  ('Stacey H'),
  ('CS_Just_Stef'),
  ('StefPac'),
  ('Stefen'),
  ('LoL PapaSnorlax'),
  ('StephC'),
  ('Stephen Gettle'),
  ('Ish'),
  ('Scuba Stephen'),
  ('BunnyFu'),
  ('Whitty'),
  ('BoarsLoreSteve'),
  ('BrownGrizz85'),
  ('Ferr0'),
  ('DeckedOutGiant'),
  ('Walsh'),
  ('ElysianNightmare'),
  ('TPSL2'),
  ('Bearzi'),
  ('BadVegas'),
  ('Marred Platypus'),
  ('FatxGui'),
  ('HybridTheory'),
  ('Stackeree'),
  ('Steven Mejia'),
  ('NVR_Azure'),
  ('InkbornTrader'),
  ('Snguyen'),
  ('Redbadge'),
  ('Constellar'),
  ('Aggrivated'),
  ('stuji'),
  ('Sunny'),
  ('lilsuzieq'),
  ('Squids'),
  ('T00sik'),
  ('Pixie Pulls'),
  ('LNGR Kolpos'),
  ('Tanya - Panda ðŸŒº Ohana'),
  ('Taryn'),
  ('Potato'),
  ('Tiggers_MoneyWizard'),
  ('Kenshinryu'),
  ('TpmcinernTSD'),
  ('Baked Goods'),
  ('Taylor R'),
  ('TTH Teresa'),
  ('TerrenceM'),
  ('TerryM'),
  ('LilThane'),
  ('LongDao'),
  ('Pizza'),
  ('T-Rox'),
  ('ThiagoSantana'),
  ('LoL_DuhTomas'),
  ('Papa Hulk'),
  ('Rizei'),
  ('Medic_Mason'),
  ('Trich710'),
  ('Tom1598'),
  ('Tiaan_WTF'),
  ('SunnyDay'),
  ('Sleepy_Otter'),
  ('Telshin'),
  ('Timmy B'),
  ('D1agram'),
  ('TimL'),
  ('Mog'),
  ('Tim M'),
  ('Tim Scarrow'),
  ('Timboslice'),
  ('Grindsonic'),
  ('His Momo-ness; Lord Momo, of the Momo Dynasty'),
  ('Tj'),
  ('TJ C.'),
  ('Icaarus'),
  ('TomandJerryRatsbury'),
  ('Tomasz'),
  ('TCP404'),
  ('Tony'),
  ('ChinoDynasty'),
  ('Topdeck Chris'),
  ('Pretty_Fox_1008'),
  ('Red'),
  ('tranquilforest'),
  ('UNINKABLESðŸ”¸Traverse Tavern'),
  ('Travboy4'),
  ('Rudrose'),
  ('SemiThere'),
  ('TravisTimm29'),
  ('Sxestrife'),
  ('Tray Soudachanh - HHM ðŸ¥'),
  ('Chase'),
  ('Trent&CoGaming'),
  ('Trent'),
  ('SaltyDuckTrevor'),
  ('AlwaysLucky'),
  ('DuhbroskiTTV'),
  ('dastree'),
  ('TrevorKTran'),
  ('LorcanaScholar'),
  ('Homura'),
  ('Nashcana_Tripp'),
  ('ShiftyMystic'),
  ('LhiteWock'),
  ('tristan2nice'),
  ('Troy'),
  ('Randy Savage'),
  ('ChanBear'),
  ('Nimble_Sloth_7701'),
  ('VoliTyl'),
  ('tycat'),
  ('Redwing445'),
  ('TPM_Tyler'),
  ('[Noninkables] Botsu'),
  ('Kronkered'),
  ('shaggypowers'),
  ('Tyler Novak'),
  ('Fugly'),
  ('ICTST8'),
  ('VArroyo'),
  ('visiechan'),
  ('WDWAuror'),
  ('Local Trash Player'),
  ('Victor'),
  ('Victorious'),
  ('MightieMinx'),
  ('vs000'),
  ('Ornate_Dragon_6486'),
  ('FoodStamps'),
  ('THG_Doogley'),
  ('ROV_Vince'),
  ('LorcanaBOI'),
  ('Vivian T'),
  ('Vo'),
  ('Wahnderful'),
  ('neurofuzz (Wally)'),
  ('Weeb Box Games'),
  ('RileysWrath'),
  ('WES_Bolero'),
  ('Wiiman1154'),
  ('Keellath'),
  ('Big Evil'),
  ('WhiteWarlock'),
  ('LB_Aphro'),
  ('Willgloyeck'),
  ('bardhub'),
  ('WillH'),
  ('Will K. / Hokage'),
  ('Will2'),
  ('WillyD'),
  ('Reverbe'),
  ('Bokachoy225'),
  ('IMP - Smpcavery'),
  ('King Cole'),
  ('W.Deane'),
  ('Whiplashxcv'),
  ('BillyYank1863'),
  ('LK_MATTERDADDY'),
  ('Strigoi86'),
  ('Skellington'),
  ('TheShirtGoblin'),
  ('Winston B'),
  ('Moluk'),
  ('TheWoodTSD'),
  ('Robert Arguelles'),
  ('Wunglu'),
  ('ChenLee'),
  ('You Know Who'),
  ('Dawnwind'),
  ('YenSid'),
  ('Human'),
  ('Ying'),
  ('Alzakiell'),
  ('TLD_Yirdboy'),
  ('Zach Bivens'),
  ('Cpt Rogers'),
  ('I&LâŸ¡Spoopmasta'),
  ('ZachFitzgerald'),
  ('ZachG07'),
  ('ZachG1'),
  ('Zach Krizan - Lucksack'),
  ('LB_Roberson'),
  ('ZachSn'),
  ('zachary w'),
  ('Zach Stone'),
  ('ZachMccoy'),
  ('ExecutiveSweets'),
  ('LoL ZigZag'),
  ('Zan Syed'),
  ('TopDeckKing45'),
  ('Zanerik'),
  ('Zarek - Ohana ðŸŒº'),
  ('I&LâŸ¡Zaven'),
  ('Clever_Kangaroo_1211'),
  ('ZeroTheHero'),
  ('Zdub22')
on conflict (name) do nothing;

-- Seed dual-color decks
insert into decks (name) values
  ('Amber/Amethyst'),
  ('Amber/Emerald'),
  ('Amber/Ruby'),
  ('Amber/Sapphire'),
  ('Amber/Steel'),
  ('Amethyst/Emerald'),
  ('Amethyst/Ruby'),
  ('Amethyst/Sapphire'),
  ('Amethyst/Steel'),
  ('Emerald/Ruby'),
  ('Emerald/Sapphire'),
  ('Emerald/Steel'),
  ('Ruby/Sapphire'),
  ('Ruby/Steel'),
  ('Sapphire/Steel')
on conflict (name) do nothing;
